CREATE TABLE products (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255),
    price      DOUBLE PRECISION,
    category   VARCHAR(255),
    emoji      VARCHAR(20),
    stock      INTEGER,
    unit_label VARCHAR(50)
);
