-- Orders table: one row per checkout
CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status       VARCHAR(50),
    subtotal     DOUBLE PRECISION NOT NULL,
    delivery_fee DOUBLE PRECISION NOT NULL,
    platform_fee DOUBLE PRECISION NOT NULL,
    total        DOUBLE PRECISION NOT NULL,
    created_at   TIMESTAMP
);

-- Order items table: one row per product line in each order
-- order_id is a foreign key → links each item back to its parent order
CREATE TABLE order_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT NOT NULL,
    product_id   BIGINT,
    product_name VARCHAR(255),
    emoji        VARCHAR(20),
    quantity     INTEGER NOT NULL,
    unit_price   DOUBLE PRECISION NOT NULL,
    item_total   DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id)
);
